
name: cuid
description: collision resisitant identifiers
version: 0.0.2
author: Levi Cook <levicook@gmail.com>
homepage: https://github.com/levicook/cuid

dev_dependencies:
  test: ^1.6.4

environment:
  sdk: '>=2.0.0 <3.0.0'
